name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        echo "::set-env name=APPLICATION_VERSION::$(grep -oE '[0-9.]+' version.sbt)"
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Release
      run: sbt "release with-defaults"
    - name: Deploy
      run: |
        terraform init -backend-config="token=$TF_TOKEN" infra
        terraform apply -auto-approve infra
      env:
        TF_WORKSPACE: uat
        TF_TOKEN: ${{ secrets.TF_TOKEN }}
        TF_VAR_application_version: ${{ env.APPLICATION_VERSION }}